spring:
  datasource:
    url: jdbc:h2:~/hateoas
    driver-class-name: org.h2.Driver
    username: pabitra
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#        generate_statistics: true
#        use_sql_comments: true
#        type: trace
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
#logging:
#  level:
#    org.springframework.orm.jpa: DEBUG
#    org.springframework.transaction: DEBUG
springdoc:
  swagger-ui:
    path: /swagger-ui/
